meta_product_name: "Beta Vision"
meta_title: "Beta Vision - Contribute to cool ideas while making money"
meta_description: "An Efficient Solution for Startups to test their beta versions and an easy way to earn money while testing."
meta_image: "lampje_betavision.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
